on:
 push:
   branches: 
     - master
jobs:
  my_file_check:
    runs-on: ubuntu-latest
    name: My test job
    steps:
      # To use this repository's private action, you must check out the repository, v2 is part of the action name
      - name: Checkout
        uses: actions/checkout@v2
      - name: CMSSW container action step
        uses: ./ # Uses an action in the root directory
        id: inspect
        with:
          file-name: 'root://eospublic.cern.ch//eos/opendata/cms/Commissioning10/MinimumBias/RECO/07JunReReco_900GeV/0000/024343EA-2891-E011-86BA-00E081791777.root'
          CMSSW_VERSION: 'CMSSW_4_2_8_lowpupatch1'   
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: ${{ steps.inspect.outputs.output-file-name }}       
      - name: Output time and name
        run: |
          echo "The time is ${{ steps.inspect.outputs.time }}"
          echo "Log file name is ${{ steps.inspect.outputs.output-file-name }}"
